### ISSUE TITLE
Stella 6.1 available

### ISSUE THREAD

**Issue by sa666666** [libretro/stella2014-libretro#58]
Sorry, not sure where to post this, since I'm not familiar with who maintain libretro cores, or your organizational structure.

Stella 6.1 has been released, and it contains upstream support for libretro.  I suggest to have this current core kept for compatibility with older hardware, and perhaps create a new repo that defaults to 6.1.

Again, not sure how you guys organize this, but I think the 6.1-based release should be the default, not this one.

**Comment by hizzlekizzle** [comment]
Hey, I saw that in your release announcement. Great news! :)

We keep this one around for platforms that can't run the new one (either because they're too slow or they don't have a modern compiler toolchain), but for platforms that can run it, we build directly from your upstream repo and it's called "stella" instead of "stella2014" like this one. That's our usual naming scheme: no year means "newest/up-to-date" and the years denote when a snapshot is from.

**Comment by sa666666** [comment]
OK, then I guess a lot of the bug reports here are no longer valid.  They've either been fixed in the latest release, or they won't be fixed at all (since we aren't doing development on the old 3.x branch anymore).
